---

# Install EPEL repo, needed for pip and other packages.
- name: Install EPEL
  yum:
    name: ['epel-release']
    state: present
  become: true
  become_user: root
  become_method: su

# Install dependencies for CWL-runner
- name: Install dependencies for cwl
  yum:
    name: ['bzip2']
    state: present
  become: true
  become_user: root
  become_method: su
  
- name: Check path in profile
  lineinfile:
    name: /etc/profile
    line: '.*/opt/anaconda/bin.*'
    state: absent
  check_mode: yes
  changed_when: false
  register: conda_path

#- name: Check - Path
#  shell: grep '/opt/anaconda/bin' /etc/profile
#  register: conda_path_exists


- name: Install Conda
  block:
    - name: Download Anaconda
      get_url:
        url: https://repo.anaconda.com/archive/Anaconda3-5.3.1-Linux-x86_64.sh
        dest: /tmp/anaconda.sh
        checksum: md5:334b43d5e8468507f123dbfe7437078f
        mode: 0550

    - name: Create conda folder
      become: True
      become_user: root 
      become_method: su
      file:
        path: /opt/anaconda`
        state: directory
        owner: root
        mode: 0755
        recurse: yes

    - name: Run the installer
      shell: /tmp/anaconda.sh -b -u -p /opt/anaconda

    - name: Remove the installer
      file:
        state: absent
        path: /tmp/install-anaconda.sh

    - name: Add anaconda bin to path
      become: True
      become_user: root 
      become_method: su
      shell: echo 'export PATH=/opt/anaconda/bin:$PATH' >> /etc/profile

    - name: conda - read permission for all
      become: True
      become_user: root 
      become_method: su
      file:
        path: /opt/anaconda
        mode: 0775
        recurse: yes

    - name: conda - execution permission for all
      become: True
      become_user: root 
      become_method: su
      file:
        path: /opt/anaconda/bin
        mode: 0775
        recurse: yes

    - name: enable conda enviroment
      become: True
      become_user: root 
      become_method: su
      file:
        src: '/opt/anaconda/etc/profile.d/conda.sh'
        dest: '/etc/profile.d/conda.sh'
        owner: root
        group: root
        mode: u=rw,g=r,o=r
        state: link
  when: not conda_path.found      

- name: check for enviroment
  shell: /opt/anaconda/bin/conda env list | grep 'cromwell_test' || true
  register: conda_env_exists
  # grep will exit with 1 when no results found. 
  # This causes the task not to halt play.
  ignore_errors: true

- name: install conda-forge channel
  shell: /opt/anaconda/bin/conda config --add channels conda-forge
  when: conda_env_exists.stdout == ""

- name: install cromwell
  shell: /opt/anaconda/bin/conda create -y -f -n cromwell_test cromwell
  when: conda_env_exists.stdout == ""
