---
# Tasks to install and configure CWL-runner


# Install EPEL repo, needed for pip and other packages.

- name: Install EPEL
  yum:
    name: ['epel-release']
    state: present
  become: yes
  become_user: root
  become_method: su


# Install dependencies for CWL-runner

- name: Install dependencies for cwl
  yum:
    name: ['python3-pip', 'python3-devel', 'python-virtualenv', 'gcc']
    state: present
  become: yes
  become_user: root
  become_method: su

# Install cwlref-runner in venv

- name: install cwl in virtualenv
  pip:
    name: cwlref-runner
    virtualenv: ~/cwl_test
    virtualenv_python: python3
