---
# Tasks to install and configure toil

# Install EPEL repo, needed for pip and other packages.
- name: Install EPEL
  dnf:
    name: ['epel-release']
    state: present
  become: true
  become_user: root
  become_method: su

# Install dependencies for CWL-runner
- name: Install dependencies for cwl
  yum:
    name: ['python3-pip', 'python3-devel', 'gcc-c++']
    state: present
  become: true
  become_user: root
  become_method: su

# Install toil
- name: install toil
  pip:
    name:
      - toil[cwl]==5.2.0
    executable: pip3
  become: true
  become_user: root
  become_method: su
