---
# Tasks to install airflow


# Install EPEL repo, needed for pip and other packages.

- name: Install EPEL
  yum:
    name: ['epel-release']
    state: present
  become: true
  become_user: root
  become_method: su


# Install dependencies for airflow

- name: Install dependencies for airflow
  yum:
    name:
      - python3-pip
      - python3-devel
      - python3-virtualenv
      - mariadb
      - openldap-devel
      - openssl-devel
      - rust
      - cargo
      - gcc
    # libmysqlclient-dev in ubuntu
    state: present
  become: true
  become_user: root
  become_method: su


# Install airflow dependencies in virtual env

- name: install airflow dependencies
  pip:
    name:
      - psutil<5.0.0,>=4.2.0'
      - six
      - pythondns
      - python-ldap
      - setuptools
      - setuptools-rust
      - wheel
    executable: pip3
  become: true
  become_user: root
  become_method: su

# Install airflow in virtual env

- name: install airflow in virtualenv
  pip:
    name: cwl-airflow
    executable: pip3
  become: true
  become_user: root
  become_method: su
