---
name: Molecule Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wfe: ['cwl', 'toil']
        python-version: [3.6]

    steps:
      - uses: actions/checkout@v2
        with:
          path: molecule_demo
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies for Molecule
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install "molecule[docker,lint,ansible]"
      - name: Molecule - Test ${{ matrix.wfe }}
        run: |
          cd molecule_demo/roles/${{ matrix.wfe }}
          molecule test
